-intstyle "ise" -incremental -lib "unisims_ver" -lib "unimacro_ver" -lib "xilinxcorelib_ver" -lib "secureip" -o "X:/ass5/cpu_tb_isim_beh.exe" -prj "X:/ass5/cpu_tb_beh.prj" "work.cpu_tb" "work.glbl" 
